const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const JSZip=require('jszip');
const {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun,AlignmentType}=require('docx');

const TEXT_MODEL=process.env.TEXT_MODEL||'gemini-3.7-flash';
const IMAGE_MODEL=process.env.IMAGE_MODEL||'gpt-image-2';
const SCRIPT_MODEL=process.env.SCRIPT_MODEL||'gemini-3.5-flash-lite';
const KYMA_BASE=process.env.KYMA_BASE||'https://api.kymaapi.com/v1';
const CONTENT_SYSTEM=fs.readFileSync(path.join(__dirname,'..','tool','prompt_content.md'),'utf8');
const SCRIPT_SYSTEM=`Bạn là biên tập viên hiệu đính transcript tiếng Việt. Trả lại đầy đủ nguyên văn ý người nói; chỉ sửa lỗi nhận dạng, thuật ngữ, chính tả, dấu câu, viết hoa, tách đoạn và bỏ từ đệm lặp vô nghĩa. Không thêm ý, không tóm tắt, không văn vẻ hóa. Chỗ không rõ giữ nguyên. Output chỉ là transcript đã hiệu đính.`;
const IMAGE_STYLE=`Clean business infographic 16:9 theo design system Pezo: nền trắng, navy #0B1F4D, blue #1261F5, card bo góc, icon line đơn giản, font sans-serif rõ nét, nhiều khoảng trắng; không photo, không 3D, không cartoon, không watermark. Không đặt tiêu đề ở đầu ảnh. Chữ trong sơ đồ phải là tiếng Việt có dấu và mỗi nhãn tối đa 5 từ.`;

const jobs=new Map(),runs=new Map();
let runRoot='';
const safe=s=>String(s||'').replace(/[\\/:*?"<>|]/g,'-').replace(/\.\./g,'-').trim().slice(0,80)||'1';
const save=j=>{const copy={...j};delete copy.api_key;fs.mkdirSync(j.dir,{recursive:true});fs.writeFileSync(path.join(j.dir,'job.json'),JSON.stringify(copy),{mode:0o600})};
function load(){if(!runRoot||!fs.existsSync(runRoot))return;for(const f of fs.readdirSync(runRoot)){const rd=path.join(runRoot,f);if(!fs.statSync(rd).isDirectory())continue;const run={id:f,jobs:[]};for(const d of fs.readdirSync(rd)){const jf=path.join(rd,d,'job.json');try{const j=JSON.parse(fs.readFileSync(jf));j.dir=path.dirname(jf);if(['queued','running'].includes(j.status)){j.status='error';j.stage='Bị gián đoạn — bấm Chạy lại'};jobs.set(j.id,j);run.jobs.push(j)}catch{}}if(run.jobs.length)runs.set(f,run)}}
const pub=j=>{const o={...j};delete o.transcript;delete o.dir;delete o.api_key;delete o.owner;return o};
const keyOf=(j,k)=>String(k||j.api_key||process.env.KYMA_API_KEY||'').trim();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function kyma(pathname,opts,key,tries=4){let last;for(let i=0;i<tries;i++){try{const r=await fetch(KYMA_BASE+pathname,{...opts,headers:{authorization:'Bearer '+key,'content-type':'application/json',...(opts.headers||{})}});const text=await r.text();if(r.ok)return text?JSON.parse(text):{};if(r.status===402||text.includes('insufficient_credits'))throw new Error('Hết credit Kyma. Bạn nạp thêm rồi bấm Chạy lại.');if([401,403].includes(r.status))throw new Error('API key Kyma không hợp lệ hoặc bị từ chối.');if(r.status===404)throw new Error('Model không tồn tại trên Kyma.');last=new Error('Kyma tạm lỗi '+r.status)}catch(e){last=e;if(/Hết credit|không hợp lệ|không tồn tại/.test(e.message))throw e}await sleep(1500*(i+1))}throw last}
async function chat(model,messages,key,extra={}){const d=await kyma('/chat/completions',{method:'POST',body:JSON.stringify({model,messages,temperature:.3,...extra})},key);return String(d.choices?.[0]?.message?.content||'').replace(/^```[a-z]*\s*|\s*```$/gi,'').trim()}
async function image(prompt,key){const d=await kyma('/images/generations',{method:'POST',body:JSON.stringify({model:IMAGE_MODEL,prompt,size:'1536x1024'})},key,3);if(d.data?.[0]?.b64_json)return Buffer.from(d.data[0].b64_json,'base64');if(d.data?.[0]?.url)return Buffer.from(await (await fetch(d.data[0].url)).arrayBuffer());const id=d.id;for(let i=0;i<100;i++){await sleep(6000);const s=await kyma('/jobs/'+id,{method:'GET'},key,2);if(s.status==='succeeded')return Buffer.from(await (await fetch(s.output.url)).arrayBuffer());if(['failed','cancelled','error'].includes(s.status))throw new Error('Tạo ảnh thất bại')}throw new Error('Tạo ảnh quá thời gian')}
function chunks(text,n=6000){text=String(text||'').trim();if(text.length<=n*1.3)return[text];const out=[];for(let i=0;i<text.length;){let e=Math.min(i+n,text.length);if(e<text.length){const w=text.slice(i,e);const cut=Math.max(w.lastIndexOf('. '),w.lastIndexOf('? '),w.lastIndexOf('! '),w.lastIndexOf('\n'));if(cut>n*.5)e=i+cut+1}out.push(text.slice(i,e).trim());i=e}return out.filter(Boolean)}
const secRe=/^##\s+(?:(\d+)\s*[.)]\s*)?(.*)$/;
const blockRe=/^\**\[(?:MINH\s*HO[ẠA]\s*[—\-–]\s*N[ÊE]N\s*C[ÓO]|[ẢA]NH\s*T[ỰU]\s*CH[ÈE]N)\]\**\s*(?:`([^`]+)`)?\s*$/i;
function slug(s,f='minh-hoa'){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase().slice(0,70)||f}
function collect(md){const lines=String(md||'').split(/\r?\n/),out=[],used=new Set();let section=0,title='';for(let i=0;i<lines.length;i++){const s=lines[i].trim(),sm=s.match(secRe);if(sm){section++;title=sm[2].trim();continue}const m=s.match(blockRe);if(!m)continue;const desc=[];for(let k=i+1;k<lines.length;k++){const t=lines[k].trim();if(!t){if(desc.length)break;continue}if(t.startsWith('#')||t==='---'||blockRe.test(t))break;desc.push(t.replace(/^[>*_\s]+|[*_\s]+$/g,''))}let name=safe(m[1]||slug(title,'muc-'+(section||1))+'.png').replace(/\s+/g,'-');if(!/\.(png|jpg|jpeg|webp|gif)$/i.test(name))name+='.png';let base=name.replace(/\.[^.]+$/,''),ext=name.slice(base.length),n=2;while(used.has(name))name=base+'-'+n+++ext;used.add(name);out.push({section:section||1,section_title:title,desc:desc.join(' '),filename:name,source:/ẢNH|ANH/i.test(s)?'upload':'ai',status:'pending',path:null,v:0})}return out}
function annotate(md){const items=collect(md);let n=0;return String(md||'').split(/\r?\n/).map(line=>blockRe.test(line.trim())&&items[n]?`**[${items[n].source==='upload'?'ẢNH TỰ CHÈN':'MINH HOẠ — NÊN CÓ'}]** \`${items[n++].filename}\``:line).join('\n')}
async function makeImage(j,it,key){try{it.status='running';save(j);const b=await image(`${IMAGE_STYLE}\nBối cảnh: ${it.section_title}\nMô tả minh hoạ: ${it.desc}`,key);const p=path.join(j.dir,it.filename);fs.writeFileSync(p,b);Object.assign(it,{status:'done',path:p,v:Date.now(),error:null})}catch(e){Object.assign(it,{status:'error',error:e.message.slice(0,300)})}save(j)}
async function processJob(j,model,makeImages){const t=Date.now();try{j.status='running';j.stage='Đang hiệu đính transcript';save(j);const fixed=await Promise.all(chunks(j.transcript).map(x=>chat(SCRIPT_MODEL,[{role:'system',content:SCRIPT_SYSTEM},{role:'user',content:x}],j.api_key,{temperature:.2,reasoning_effort:'low'})));j.script=fixed.join('\n\n');j.stage='Đang viết file nội dung';save(j);let md=await chat(model,[{role:'system',content:CONTENT_SYSTEM},{role:'user',content:j.script}],j.api_key);const at=md.indexOf('## ');if(at>=0)md=md.slice(at);j.content_md=annotate(md);j.illustrations=collect(j.content_md);j.stage=makeImages&&j.illustrations.length?`Đang tạo ${j.illustrations.length} ảnh minh hoạ`:'Xong';save(j);if(makeImages)await Promise.all(j.illustrations.map(it=>makeImage(j,it,j.api_key)));j.status='done';j.stage='Xong — mời rà soát nội dung';j.elapsed=Math.round((Date.now()-t)/1000);save(j)}catch(e){j.status='error';j.stage='Lỗi';j.error=e.message.slice(0,500);j.elapsed=Math.round((Date.now()-t)/1000);save(j)}}
function inline(text){const out=[];for(const p of String(text).split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/)){if(!p)continue;if(p.startsWith('**'))out.push(new TextRun({text:p.slice(2,-2),bold:true}));else if(p.startsWith('*'))out.push(new TextRun({text:p.slice(1,-1),italics:true}));else out.push(new TextRun(p.replace(/^`|`$/g,'')))}return out}
async function docBuffer(text,illustrations=[]){const children=[];let sec=0;const bySec={};for(const it of illustrations.filter(x=>x.status==='done'&&x.path)) (bySec[it.section]??=[]).push(it);async function flush(){for(const it of bySec[sec]||[]){try{children.push(new Paragraph({children:[new ImageRun({data:fs.readFileSync(it.path),transformation:{width:640,height:400},type:'png'})],alignment:AlignmentType.CENTER}))}catch{}}}for(const raw of String(text||'').split(/\r?\n/)){const s=raw.trim();if(!s)continue;if(s.startsWith('## ')){await flush();sec++;children.push(new Paragraph({text:s.slice(3),heading:HeadingLevel.HEADING_1}));continue}if(s.startsWith('### ')){children.push(new Paragraph({text:s.slice(4),heading:HeadingLevel.HEADING_2}));continue}if(blockRe.test(s))continue;if(s.startsWith('> ')){children.push(new Paragraph({children:inline(s.slice(2)),style:'IntenseQuote'}));continue}if(/^[-*]\s/.test(s)){children.push(new Paragraph({children:inline(s.slice(2)),bullet:{level:0}}));continue}children.push(new Paragraph({children:inline(s)}))}await flush();return Packer.toBuffer(new Document({sections:[{children}]}))}
async function zipRun(run){const z=new JSZip();for(const j of run.jobs){const f=z.folder(safe(j.name));f.file('noi-dung.docx',await docBuffer(j.content_md,j.illustrations));f.file('full-transcript.docx',await docBuffer(j.script));for(const it of j.illustrations.filter(x=>x.status==='done'&&x.path&&fs.existsSync(x.path)))f.file(it.filename,fs.readFileSync(it.path))}return z.generateAsync({type:'nodebuffer',compression:'DEFLATE'})}

function mount(app,{storage,paidBuyer}){runRoot=path.join(storage,'runs');fs.mkdirSync(runRoot,{recursive:true});load();const own=(req,id)=>{const j=jobs.get(id);if(!j||j.owner!==req.buyer.email)throw Object.assign(new Error('not found'),{status:404});return j};
 app.post('/api/check-key',paidBuyer,async(req,res)=>{try{const key=String(req.body?.key||'').trim();if(!key)return res.json({ok:false,message:'Chưa nhập key'});await chat(SCRIPT_MODEL,[{role:'user',content:'ok'}],key,{max_tokens:1});res.json({ok:true,message:'Key dùng được'})}catch(e){res.json({ok:false,message:e.message})}});
 app.get('/api/models',paidBuyer,(req,res)=>res.json({text_model:TEXT_MODEL,image_model:IMAGE_MODEL,server_key:false}));
 app.post('/api/run',paidBuyer,(req,res)=>{const key=String(req.get('x-kyma-key')||'').trim();if(!key)return res.status(400).json({detail:'Chưa có API key Kyma.'});const id=crypto.randomBytes(4).toString('hex'),run={id,jobs:[]},rd=path.join(runRoot,id);fs.mkdirSync(rd,{recursive:true});(req.body.transcripts||[]).slice(0,10).forEach((t,i)=>{const name=safe(t.name||i+1),j={id:`${id}-${i+1}`,index:i+1,name,dir:path.join(rd,name),owner:req.buyer.email,transcript:String(t.text||''),status:'queued',stage:'Đang chờ',script:'',content_md:'',illustrations:[],error:null,elapsed:0,text_model:req.body.text_model||TEXT_MODEL,api_key:key};jobs.set(j.id,j);run.jobs.push(j);save(j);setImmediate(()=>processJob(j,j.text_model,req.body.make_images!==false))});runs.set(id,run);res.json({run_id:id,jobs:run.jobs.map(x=>x.id)})});
 app.get('/api/status/:id',paidBuyer,(req,res)=>{const r=runs.get(req.params.id);if(!r||r.jobs.some(j=>j.owner!==req.buyer.email))return res.status(404).json({detail:'run không tồn tại'});res.json({run_id:r.id,jobs:r.jobs.map(pub)})});
 app.post('/api/job/:id/save',paidBuyer,(req,res)=>{try{const j=own(req,req.params.id);if(req.body.content_md!=null)j.content_md=annotate(req.body.content_md);if(req.body.script!=null)j.script=String(req.body.script);save(j);res.json({ok:true})}catch(e){res.status(e.status||500).json({detail:'không tìm thấy'})}});
 app.post('/api/job/:id/resync-images',paidBuyer,(req,res)=>{try{const j=own(req,req.params.id),key=keyOf(j,req.get('x-kyma-key'));j.illustrations=collect(j.content_md);j.status='running';j.stage=`Đang tạo ${j.illustrations.length} ảnh`;save(j);setImmediate(async()=>{await Promise.all(j.illustrations.map(it=>makeImage(j,it,key)));j.status='done';j.stage='Xong';save(j)});res.json({ok:true,queued:j.illustrations.length})}catch(e){res.status(e.status||500).json({detail:'không tìm thấy'})}});
 app.post('/api/job/:id/image/:file/regen',paidBuyer,(req,res)=>{try{const j=own(req,req.params.id),it=j.illustrations.find(x=>x.filename===req.params.file);if(!it)return res.status(404).json({detail:'không có ảnh'});j.status='running';save(j);setImmediate(async()=>{await makeImage(j,it,keyOf(j,req.get('x-kyma-key')));j.status='done';save(j)});res.json({ok:true})}catch(e){res.status(e.status||500).json({detail:'không tìm thấy'})}});
 app.get('/api/job/:id/image/:file',paidBuyer,(req,res)=>{try{const j=own(req,req.params.id),it=j.illustrations.find(x=>x.filename===req.params.file),p=it?.path;if(!p||!fs.existsSync(p))return res.status(404).end();res.set('cache-control','no-store').sendFile(p)}catch{res.status(404).end()}});
 app.post('/api/job/:id/image/:file/delete',paidBuyer,(req,res)=>{try{const j=own(req,req.params.id),it=j.illustrations.find(x=>x.filename===req.params.file);if(!it)return res.status(404).json({detail:'không có ảnh'});try{fs.unlinkSync(it.path)}catch{}it.status='deleted';it.path=null;save(j);res.json({ok:true})}catch{res.status(404).json({detail:'không tìm thấy'})}});
 app.post('/api/job/:id/image/:file/rename',paidBuyer,(req,res)=>{try{const j=own(req,req.params.id),it=j.illustrations.find(x=>x.filename===req.params.file);if(!it)return res.status(404).json({detail:'không có ảnh'});let name=safe(req.body.name);if(!/\.[a-z]{3,4}$/i.test(name))name+='.png';if(it.path&&fs.existsSync(it.path)){const np=path.join(j.dir,name);fs.renameSync(it.path,np);it.path=np}j.content_md=j.content_md.replaceAll('`'+it.filename+'`','`'+name+'`');it.filename=name;save(j);res.json({ok:true,filename:name})}catch(e){res.status(400).json({detail:e.message})}});
 app.post('/api/job/:id/upload-image-json',paidBuyer,(req,res)=>uploadJson(req,res,own(req,req.params.id),null));
 app.post('/api/job/:id/image/:file/replace-json',paidBuyer,(req,res)=>uploadJson(req,res,own(req,req.params.id),req.params.file));
 async function uploadJson(req,res,j,replace){try{const m=String(req.body.data||'').match(/^data:image\/[\w.+-]+;base64,(.+)$/);if(!m)return res.status(400).json({detail:'ảnh không hợp lệ'});const b=Buffer.from(m[1],'base64');if(!b.length||b.length>5*1024*1024)return res.status(400).json({detail:'ảnh tối đa 5MB'});let name=replace||safe(req.body.name||'anh-chen-them.png');if(!/\.(png|jpe?g|webp|gif)$/i.test(name))name+='.png';const p=path.join(j.dir,name);fs.writeFileSync(p,b);let it=j.illustrations.find(x=>x.filename===replace);if(it)Object.assign(it,{path:p,status:'done',source:'upload',v:Date.now()});else j.illustrations.push({section:Number(req.body.section)||1,section_title:'',desc:String(req.body.desc||''),filename:name,source:'upload',status:'done',path:p,v:Date.now()});save(j);res.json({ok:true,filename:name})}catch(e){res.status(400).json({detail:e.message})}}
 app.get('/api/download/:id',paidBuyer,async(req,res)=>{const r=runs.get(req.params.id);if(!r||r.jobs.some(j=>j.owner!==req.buyer.email))return res.status(404).end();const b=await zipRun(r);res.type('application/zip').attachment(`pezo-${r.id}.zip`).send(b)});
 app.get('/api/job/:id/download',paidBuyer,async(req,res)=>{try{const j=own(req,req.params.id),b=await zipRun({jobs:[j]});res.type('application/zip').attachment(`${safe(j.name)}.zip`).send(b)}catch{res.status(404).end()}});
}
module.exports={mount};
